### ISSUE TITLE
feat: 增强AI识别commit类型的准确性,支持所有标准类型(如refactor、fix等)

### ISSUE THREAD

**Issue by lapse12** [Undertone0809/gcop#85]
## 🚀 Feature Request

增强AI识别commit主要类型的能力,支持更多标准的commit类型,如refactor、fix等。

## 🔈 Motivation

目前AI在识别commit的主要类型时有时不够准确。通过支持更多标准的commit类型,可以提高AI分类的准确性和实用性,使工具能更好地满足开发者的需求。

## 📎 Additional context

建议下拉列表对于每种标准类型都生成一个 commit：
- feat: 新功能
- fix: 修复bug
- docs: 文档更新
- style: 代码格式修改
- refactor: 代码重构
- perf: 性能优化
- test: 测试相关
- build: 构建系统或外部依赖变更
- ci: CI配置变更

**Comment by Undertone0809** [comment]
想到可以构建一个 diff benchmarks 来更好的评估效果。

**Comment by Undertone0809** [comment]
想到可以构建一个 diff benchmarks 来更好的评估效果。

**Comment by Undertone0809** [comment]
ref: #111
